PodCast/Models/EpisodeDetailsViewModel.cs
using PodCast.DataContext.Entities;

namespace PodCast.Models
{
    public class EpisodeDetailsViewModel
    {
        public Episode? Episode { get; set; }
        public List<Episode> RelatedEpisodes { get; set; } = [];
    }
}

PodCast/Models/EpisodeViewModel.cs
using PodCast.DataContext.Entities;

namespace PodCast.Models
{
    public class EpisodeViewModel
    {
        public List<Episode> Episodes { get; set; } = [];
        public List<Episode> TrendingEpisodes { get; set; } = [];
    }
}

PodCast/Models/ErrorViewModel.cs
namespace PodCast.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PodCast/Models/FooterViewModel.cs
using PodCast.DataContext.Entities;

namespace PodCast.Models
{
    public class FooterViewModel
    {
        public List<Social> Socials { get; set; } = [];
        public Bio? Bio { get; set; }
    }
}

PodCast/Models/HomeViewModel.cs
using PodCast.DataContext.Entities;

namespace PodCast.Models
{
    public class HomeViewModel
    {
        public List<Speaker> Speakers { get; set; } = [];
        public List<Topic> Topics { get; set; } = [];
        public List<Episode> Episodes { get; set; } = [];
        public List<Episode> TrendingEpisodes {  get; set; } = [];
    }
}

PodCast/Controllers/EpisodeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PodCast.DataContext;
using PodCast.Models;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace PodCast.Controllers
{
    public class EpisodeController : Controller
    {
        private readonly AppDbContext _dbContext;

        public EpisodeController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var episodes = _dbContext.Episodes
                .Include(x => x.Speaker)
                .ThenInclude(x => x!.SpeakerProfessions)
                .ThenInclude(x => x.Profession)
                .Take(2)
                .ToList();
            var trendingEpisodes = _dbContext.Episodes.Take(2).ToList();
            var model = new EpisodeViewModel
            {
                Episodes = episodes,
                TrendingEpisodes = trendingEpisodes
            };

            return View(model);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
                return NotFound();

            var episode = _dbContext.Episodes.FirstOrDefault(x=>x.Id == id);

            if (episode == null)
                return NotFound();

            var relatedEpisodes = _dbContext.Episodes.Skip(2).ToList();

            var model = new EpisodeDetailsViewModel
            {
                Episode = episode,
                RelatedEpisodes = relatedEpisodes
            };

            return View(model);
        }

        public IActionResult Partial(int skip)
        {
            var episodes = _dbContext.Episodes
                .Include(x => x.Speaker)
                .ThenInclude(x => x!.SpeakerProfessions)
                .ThenInclude(x => x.Profession)
                .Skip(skip)
                .Take(2)
                .ToList();

            //return Json(episodes,new JsonSerializerOptions { ReferenceHandler = ReferenceHandler.IgnoreCycles});

            return PartialView("_EpisodePartialForLoadMore", episodes);
        }
    }

    
}

PodCast/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PodCast.Models;
using PodCast.DataContext;
using Microsoft.EntityFrameworkCore;

namespace PodCast.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _dbContext;

        public HomeController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var model = new HomeViewModel
            {
                Speakers = _dbContext.Speakers.ToList(),
                Topics = _dbContext.Topics.ToList(),
                Episodes = _dbContext.Episodes
                    .Include(e => e.Speaker)
                    .Include(e => e.Topic)
                    .OrderByDescending(e => e.Id)
                    .Take(2)
                    .ToList(),
                TrendingEpisodes = _dbContext.Episodes.Take(2).ToList(),
            };
            return View(model);
        }
    }
}

PodCast/ViewComponents/EpisodeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PodCast.DataContext;
using PodCast.DataContext.Entities;

namespace PodCast.ViewComponents
{
    public class EpisodeViewComponent : ViewComponent
    {
        private readonly AppDbContext _dbContext;

        public EpisodeViewComponent(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IViewComponentResult> InvokeAsync(List<Episode> episodes)
        {
            //var episodes = _dbContext.Episodes.ToList();

            return View(episodes);
        }
    }
}

PodCast/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PodCast.DataContext;
using PodCast.Models;

namespace PodCast.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly AppDbContext _dbContext;

        public FooterViewComponent(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var socials = _dbContext.Socials.ToList();
            var bio = _dbContext.Bios.FirstOrDefault();

            var model = new FooterViewModel
            {
                Socials = socials,
                Bio = bio
            };

            return View(model);
        }
    }
}

PodCast/Views/Episode/Details.cshtml
@{
    EpisodeDetailsViewModel model = Model;
    var episode = model.Episode;
    var relatedEpisodes = model.RelatedEpisodes;
}

<header class="site-header d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12 text-center">

                <h2 class="mb-0">Detail Page</h2>
            </div>

        </div>
    </div>
</header>


<section class="latest-podcast-section section-padding pb-0" id="section_2">
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-lg-10 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Daily talk</h4>
                </div>

                <div class="row">
                    <div class="col-lg-3 col-12">
                        <div class="custom-block-icon-wrap">
                            <div class="custom-block-image-wrap custom-block-image-detail-page">
                                <img src="~/images/podcast/@episode?.CoverImagePath" class="custom-block-image img-fluid" alt="">
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-9 col-12">
                        <div class="custom-block-info">
                            <div class="custom-block-top d-flex mb-1">
                                <small class="me-4">
                                    <a href="#">
                                        <i class="bi-play"></i>
                                        Play now
                                    </a>
                                </small>

                                <small>
                                    <i class="bi-clock-fill custom-icon"></i>
                                    50 Minutes
                                </small>

                                <small class="ms-auto">Episode <span class="badge">15</span></small>
                            </div>

                            <h2 class="mb-2">Modern Vintage</h2>

                            <p>What is Content Marketing? If you are wondering what content marketing is all about, this is the place to start.</p>

                            <p>You are not allowed to redistribute this template ZIP file on any other template collection website. Please contact TemplateMo for more information.</p>

                            <p>Pod Talk HTML CSS Template is made by Bootstrap v5.2.2 framework. You are allowed to modify and use this template for your business websites.</p>

                            <div class="profile-block profile-detail-block d-flex flex-wrap align-items-center mt-5">
                                <div class="d-flex mb-3 mb-lg-0 mb-md-0">
                                    <img src="images/profile/woman-posing-black-dress-medium-shot.jpg" class="profile-block-image img-fluid" alt="">

                                    <p>
                                        Elsa
                                        <img src="images/verified.png" class="verified-image img-fluid" alt="">
                                        <strong>Influencer</strong>
                                    </p>
                                </div>

                                <ul class="social-icon ms-lg-auto ms-md-auto">
                                    <li class="social-icon-item">
                                        <a href="#" class="social-icon-link bi-instagram"></a>
                                    </li>

                                    <li class="social-icon-item">
                                        <a href="#" class="social-icon-link bi-twitter"></a>
                                    </li>

                                    <li class="social-icon-item">
                                        <a href="#" class="social-icon-link bi-whatsapp"></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>


<section class="related-podcast-section section-padding">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Related episodes</h4>
                </div>
            </div>

            @*@await Component.InvokeAsync("Episode", relatedEpisodes)*@
            <partial name="_EpisodePartial" model="@relatedEpisodes"></partial>
        </div>
    </div>
</section>

PodCast/Views/Episode/Index.cshtml
@{
    EpisodeViewModel model = Model;
    var episodes = model.Episodes;
    var trendingEpisodes = model.TrendingEpisodes;
}

<header class="site-header d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12 text-center">

                <h2 class="mb-0">Listing Page</h2>
            </div>

        </div>
    </div>
</header>


<section class="latest-podcast-section section-padding" id="section_2">
    <div class="container">
        <div class="row justify-content-center" id="episodeContainer">

            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Lastest episodes</h4>
                </div>
            </div>

            @foreach (var item in episodes)
            {
                <div class="col-lg-6 col-12 mb-4 mb-lg-0">
                    <div class="custom-block d-flex">
                        <div class="">
                            <div class="custom-block-icon-wrap">
                                <div class="section-overlay"></div>
                                <a href="detail-page.html" class="custom-block-image-wrap">
                                    <img src="~/images/podcast/@item.CoverImagePath" class="custom-block-image img-fluid" alt="">

                                    <a href="#" class="custom-block-icon">
                                        <i class="bi-play-fill"></i>
                                    </a>
                                </a>
                            </div>

                            <div class="mt-2">
                                <a href="#" class="btn custom-btn">
                                    Subscribe
                                </a>
                            </div>
                        </div>

                        <div class="custom-block-info">
                            <div class="custom-block-top d-flex mb-1">
                                <small class="me-4">
                                    <i class="bi-clock-fill custom-icon"></i>
                                    @item.DurationMinutes Minutes
                                </small>

                                <small>Episode <span class="badge">15</span></small>
                            </div>

                            <h5 class="mb-2">
                                <a href="detail-page.html">
                                    @item.Title
                                </a>
                            </h5>

                            <div class="profile-block d-flex">
                                <img src="~/images/profile/@item.Speaker?.ProfileImagePath" class="profile-block-image img-fluid" alt="">

                                <p>
                                    @item.Speaker?.Name
                                    <img src="images/verified.png" class="verified-image img-fluid" alt="">
                                    <br />
                                    @foreach (var p in item.Speaker?.SpeakerProfessions ?? [])
                                    {
                                        <strong style="display:inline">@p.Profession?.Name</strong>
                                    }
                                </p>
                            </div>

                            <p class="mb-0">Lorem Ipsum dolor sit amet consectetur</p>

                            <div class="custom-block-bottom d-flex justify-content-between mt-3">
                                <a href="#" class="bi-headphones me-1">
                                    <span>120k</span>
                                </a>

                                <a href="#" class="bi-heart me-1">
                                    <span>42.5k</span>
                                </a>

                                <a href="#" class="bi-chat me-1">
                                    <span>11k</span>
                                </a>

                                <a href="#" class="bi-download">
                                    <span>50k</span>
                                </a>
                            </div>
                        </div>

                        <div class="d-flex flex-column ms-auto">
                            <a href="#" class="badge ms-auto">
                                <i class="bi-heart"></i>
                            </a>

                            <a href="#" class="badge ms-auto">
                                <i class="bi-bookmark"></i>
                            </a>
                        </div>
                    </div>
                </div>
            }
               
            
        </div>
        <div style="width:300px; margin:0 auto; justify-content:center;display:flex">

            <button class="btn btn-primary" id="loadMore" style="margin-top:20px">Load more</button>
        </div>
    </div>
</section>


<section class="trending-podcast-section section-padding pt-0">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Trending episodes</h4>
                </div>
            </div>

            <partial name="_EpisodePartial" model="@trendingEpisodes"></partial>

        </div>
    </div>
</section>

<script>
    const loadMore = document.getElementById("loadMore");
    const episodeContainer = document.getElementById("episodeContainer");
    let skip = 2;
    loadMore.addEventListener('click',function(){
        fetch(`https://localhost:7170/episode/partial?skip=${skip}`)
        .then(response=>response.text())
        .then(html=>{
            episodeContainer.innerHTML+=html;
        });
    });

    function fillProfessions(professions){
        let l="";
        for (let p of professions)
        {
            l+=`<strong style="display:inline">${p.Profession.Name}</strong>`;
        }

        return l;
    }
</script>

PodCast/Views/Home/Index.cshtml
@model PodCast.Models.HomeViewModel

<section class="hero-section">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12">
                <div class="text-center mb-5 pb-2">
                    <h1 class="text-white">Listen to Pod Talk</h1>

                    <p class="text-white">Listen it everywhere. Explore your fav podcasts.</p>

                    <a href="#section_2" class="btn custom-btn smoothscroll mt-3">Start listening</a>
                </div>

                <div class="owl-carousel owl-theme">
                    @foreach (var speaker in Model.Speakers)
                    {
                        <div class="owl-carousel-info-wrap item">
                            <img src="~/images/profile/@speaker.ProfileImagePath" class="owl-carousel-image img-fluid" alt="@speaker.Name">

                            <div class="owl-carousel-info">
                                <h4 class="mb-2">@speaker.Name</h4>
                                @if (speaker.SpeakerProfessions != null)
                                {
                                    foreach (var sp in speaker.SpeakerProfessions)
                                    {
                                        <span class="badge">@sp.Profession?.Name</span>
                                    }
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>

        </div>
    </div>
</section>


<section class="latest-podcast-section section-padding pb-0" id="section_2">
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Lastest episodes</h4>
                </div>
            </div>

            @foreach (var episode in Model.Episodes)
            {
                <div class="col-lg-6 col-12 mb-4 mb-lg-0">
                    <div class="custom-block d-flex">
                        <div class="">
                            <div class="custom-block-icon-wrap">
                                <div class="section-overlay"></div>
                                <a asp-controller="episode" asp-action="details" asp-route-id="@episode.Id" class="custom-block-image-wrap">
                                    <img src="~/images/podcast/@episode.CoverImagePath" class="custom-block-image img-fluid" alt="@episode.Title">

                                    <a href="#" class="custom-block-icon">
                                        <i class="bi-play-fill"></i>
                                    </a>
                                </a>
                            </div>

                            <div class="mt-2">
                                <a href="#" class="btn custom-btn">
                                    Subscribe
                                </a>
                            </div>
                        </div>

                        <div class="custom-block-info">
                            <div class="custom-block-top d-flex mb-1">
                                <small class="me-4">
                                    <i class="bi-clock-fill custom-icon"></i>
                                    @episode.DurationMinutes Minutes
                                </small>

                                <small>Episode <span class="badge">@episode.Id</span></small>
                            </div>

                            <h5 class="mb-2">
                                <a asp-controller="episode" asp-action="details" asp-route-id="@episode.Id">@episode.Title</a>
                            </h5>

                            <div class="profile-block d-flex">
                                <img src="~/images/profile/@episode.Speaker?.ProfileImagePath" class="profile-block-image img-fluid" alt="@episode.Speaker?.Name">

                                <p>
                                    @episode.Speaker?.Name
                                </p>
                            </div>

                            <div class="custom-block-bottom d-flex justify-content-between mt-3">
                                <a href="#" class="bi-headphones me-1">
                                    <span>@episode.ListeningCount</span>
                                </a>

                                <a href="#" class="bi-heart me-1">
                                    <span>@episode.LikeCount</span>
                                </a>

                                <a href="#" class="bi-download">
                                    <span>@episode.DownloadCount</span>
                                </a>
                            </div>
                        </div>

                        <div class="d-flex flex-column ms-auto">
                            <a href="#" class="badge ms-auto">
                                <i class="bi-heart"></i>
                            </a>

                            <a href="#" class="badge ms-auto">
                                <i class="bi-bookmark"></i>
                            </a>
                        </div>
                    </div>
                </div>
            }
      
        </div>
    </div>
</section>


<section class="topics-section section-padding pb-0" id="section_3">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Topics</h4>
                </div>
            </div>

            @foreach (var topic in Model.Topics)
            {
                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                    <div class="custom-block custom-block-overlay">
                        <a href="detail-page.html" class="custom-block-image-wrap">
                            <img src="~/images/topics/@topic.CoverImageUrl" class="custom-block-image img-fluid" alt="@topic.Name">
                        </a>

                        <div class="custom-block-info custom-block-overlay-info">
                            <h5 class="mb-1">
                                <a href="listing-page.html">@topic.Name</a>
                            </h5>

                            <p class="badge mb-0">@topic.Episodes?.Count() Episodes</p>
                        </div>
                    </div>
                </div>
            }
       
        </div>
    </div>
</section>


<section class="trending-podcast-section section-padding">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Trending episodes</h4>
                </div>
            </div>
            @*@await Component.InvokeAsync("Episode",Model.TrendingEpisodes)*@
            <partial name="_EpisodePartial" model="@Model.TrendingEpisodes"></partial>
        </div>
    </div>
</section>

PodCast/Views/Shared/Components/Footer/Default.cshtml
@{
    FooterViewModel model = Model;
    var socials = model.Socials;
    var bio = model.Bio;
}
<footer class="site-footer">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 col-12 mb-5 mb-lg-0">
                <div class="subscribe-form-wrap">
                    <h6>Subscribe. Every weekly.</h6>

                    <form class="custom-form subscribe-form" action="#" method="get" role="form">
                        <input type="email" name="subscribe-email" id="subscribe-email" class="form-control" placeholder="Email Address" required="">

                        <div class="col-lg-12 col-12">
                            <button type="submit" class="form-control" id="submit">Subscribe</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-12 mb-4 mb-md-0 mb-lg-0">
                <h6 class="site-footer-title mb-3">Contact</h6>

                <p class="mb-2"><strong class="d-inline me-2">Phone:</strong> @bio?.MobileNumber1</p>

                <p>
                    <strong class="d-inline me-2">Email:</strong>
                    <a href="#">@bio?.Email</a>
                </p>
            </div>

            <div class="col-lg-3 col-md-6 col-12">
                <h6 class="site-footer-title mb-3">Download Mobile</h6>

                <div class="site-footer-thumb mb-4 pb-2">
                    <div class="d-flex flex-wrap">
                        <a href="#">
                            <img src="images/app-store.png" class="me-3 mb-2 mb-lg-0 img-fluid" alt="">
                        </a>

                        <a href="#">
                            <img src="images/play-store.png" class="img-fluid" alt="">
                        </a>
                    </div>
                </div>

                <h6 class="site-footer-title mb-3">Social</h6>

                <ul class="social-icon">
                    @foreach(var item in socials)
                    {
                        <li class="social-icon-item">
                            <a href="@item.Url" class="@item.IconClass"></a>
                        </li>
                    }
                </ul>
            </div>

        </div>
    </div>

    <div class="container pt-5">
        <div class="row align-items-center">

            <div class="col-lg-2 col-md-3 col-12">
                <a class="navbar-brand" href="index.html">
                    <img src="~/images/@bio?.LogoUrl" class="logo-image img-fluid" alt="templatemo pod talk">
                </a>
            </div>

            <div class="col-lg-7 col-md-9 col-12">
                <ul class="site-footer-links">
                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Homepage</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Browse episodes</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Help Center</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Contact Us</a>
                    </li>
                </ul>
            </div>

            <div class="col-lg-3 col-12">
                <p class="copyright-text mb-0">
                    Copyright © 2036 Talk Pod Company
                    <br><br>
                    Design: <a rel="nofollow" href="https://templatemo.com/page/1" target="_parent">TemplateMo</a>
                </p>
            </div>
        </div>
    </div>
</footer>

PodCast/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pod Talk - Free Bootstrap 5 CSS Template</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&family=Sono:wght@200;300;400;500;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/css/bootstrap-icons.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">

    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">

    <link href="~/css/templatemo-pod-talk.css" rel="stylesheet">

    <!--

    TemplateMo 584 Pod Talk

    https://templatemo.com/tm-584-pod-talk

    -->
</head>

<body>

    <main>

        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand me-lg-5 me-0" href="index.html">
                    <img src="images/pod-talk-logo.png" class="logo-image img-fluid" alt="templatemo pod talk">
                </a>

                <form action="#" method="get" class="custom-form search-form flex-fill me-3" role="search">
                    <div class="input-group input-group-lg">
                        <input name="search" type="search" class="form-control" id="search" placeholder="Search Podcast" aria-label="Search">

                        <button type="submit" class="form-control" id="submit">
                            <i class="bi-search"></i>
                        </button>
                    </div>
                </form>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="home" asp-action="index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="episode" asp-action="index">Episodes</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="contact.html">Contact</a>
                        </li>
                    </ul>

                    <div class="ms-4">
                        <a href="#section_3" class="btn custom-btn custom-border-btn smoothscroll">Get started</a>
                    </div>
                </div>
            </div>
        </nav>
            @RenderBody()
         </main>

         @await Component.InvokeAsync("Footer")


        <!-- JAVASCRIPT FILES -->
        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/owl.carousel.min.js"></script>
        <script src="~/js/custom.js"></script>

    </body>
</html>